var table = {
	monday:{
		"ภาษาอังกฤษ":{
			"subject":"อ20205",
			"room":"536",
			"teacher":"Ashley",
			"time":1,
			"day":1
		},
		"ภาษาจีน":{
			"subject":"จ20201",
			"room":"536",
			"teacher":"สาวิตรี",
			"time":2,
			"day":1
		},
		"คณิตศาสตร์เพิ่มพูน":{
			"subject":"ค22111",
			"room":"536",
			"teacher":"เวียงทอง",
			"time":3,
			"day":1
		},
		"$พักกลางวัน":null,
		"สังคมศึกษา":{
			"subject":"ส22101",
			"room":"536",
			"teacher":"ธญศศิ",
			"time":5,
			"day":1
		},
		"คณิตศาสตร์":{
			"subject":"ค22101",
			"room":"536",
			"teacher":"อัญชลี",
			"time":6,
			"day":1
		},
		"วิทยาศาสตร์":{
			"subject":"ว22011",
			"room":"521",
			"teacher":"รัตนพร",
			"time":7,
			"day":1
		},
		"วิทยาศาสตร์":{
			"subject":"ว22101",
			"room":"521",
			"teacher":"รัตนพร",
			"time":8,
			"day":1
		},
		"$5ส":null,
		null:null
	},
	tuesday:{
		"คณิตศาสตร์เพิ่มพูน":{
			"subject":"ค22111",
			"room":"536",
			"teacher":"เวียงทอง",
			"time":1,
			"day":2
		},
		"ภาษาอังกฤษ":{
			"subject":"อ22101",
			"room":"536",
			"teacher":"ศุภลักษณ์",
			"time":2,
			"day":2
		},
		"แนะแนว":{
			"subject":"ก22901",
			"room":"536",
			"teacher":"รัชดาพร",
			"time":3,
			"day":2
		},
		"$พักกลางวัน":null,
		"ศิลปะ":{
			"subject":"ศ22101",
			"room":"ศ1",
			"teacher":"มุกมณี",
			"time":5,
			"day":2
		},
		"ศิลปะ":{
			"subject":"ศ22101",
			"room":"ศ1",
			"teacher":"มุกมณี",
			"time":6,
			"day":2
		},
		"สังคมศึกษา":{
			"subject":"ส22101",
			"room":"536",
			"teacher":"ธญศศิ",
			"time":7,
			"day":2
		},
		"คณิตศาสตร์ประยุกต์":{
			"subject":"ค20233",
			"room":"536",
			"teacher":"ชโลม",
			"time":8,
			"day":2
		},
		null:null,
	},
	wednesday:{
		"ภาษาไทย":{
			"subject":"ท22101",
			"room":"536",
			"teacher":"พนัชกร",
			"time":1,
			"day":3
		},
		"เคมี":{
			"subject":"20207",
			"room":"536",
			"teacher":"อาทิตย์",
			"time":2,
			"day":3
		},
		"เคมี":{
			"subject":"20207",
			"room":"536",
			"teacher":"อาทิตย์",
			"time":3,
			"day":3
		},
		"$พักกลางวัน":null,
		"วิทย์ทักษะ":{
			"subject":"ว22205",
			"room":"536",
			"teacher":"ปิยวัฒน์",
			"time":5,
			"day":3
		},
		"คณิตศาสตร์":{
			"subject":"ค22101",
			"room":"536",
			"teacher":"อัญชลี",
			"time":6,
			"day":3
		},
		"ภาษาอังกฤษ":{
			"subject":"อ22101",
			"room":"536",
			"teacher":"ศุภลักษณ์",
			"time":7,
			"day":3
		},
		"$ชุมนุม":null,
		"$5ส":null,
		null:null
	},
	thursday:{
		"พละศึกษา":{
			"subject":"พ22101",
			"room":"พ.1",
			"teacher":"พัฒนชาติ",
			"time":1,
			"day":4
		},
		"คณิตศาสตร์เพิ่มพูน":{
			"subject":"ค22111",
			"room":"536",
			"teacher":"เวียงทอง",
			"time":2,
			"day":4
		},
		"ประวัติศาสตร์":{
			"subject":"ส22111",
			"room":"536",
			"teacher":"เฉลิมขวัญ",
			"time":3,
			"day":4
		},
		"$พักกลางวัน":null,
		"ภาษาอังกฤษ":{
			"subject":"อ22101",
			"room":"536",
			"teacher":"ศุภลักษณ์",
			"time":5,
			"day":4
		},
		"สังคมศึกษา":{
			"subject":"ส22101",
			"room":"416",
			"teacher":"ธญศศิ",
			"time":6,
			"day":4
		},
		"ภาษาไทย":{
			"subject":"ท22101",
			"room":"416",
			"teacher":"พนัชกร",
			"time":7,
			"day":4
		},
		"$ลูกเสือ":null,
		"$บำเพ็ญประโยชน์":null,
		null:null,
	},
	friday:{
		"การงานอาชีพ":{
			"subject":"ง22111",
			"room":"536",
			"teacher":"กุญภัฎ",
			"time":1,
			"day":5
		},
		"คณิตศาสตร์":{
			"subject":"ค22101",
			"room":"536",
			"teacher":"อัญชลี",
			"time":2,
			"day":5
		},
		"ภาษาไทย":{
			"subject":"ท22101",
			"room":"536",
			"teacher":"พนัชกร",
			"time":3,
			"day":5
		},
		"$พักกลางวัน":null,
		"สุขศึกษา":{
			"subject":"พ22101",
			"room":"536",
			"teacher":"ทัศนีย์",
			"time":5,
			"day":5
		},
		"วิทยาศาสตร์":{
			"subject":"ว22101",
			"room":"536",
			"teacher":"รัตนพร",
			"time":6,
			"day":5
		},
		"คอมพิวเตอร์":{
			"subject":"ว22171",
			"room":"คอม 1",
			"teacher":"ชฎาพร",
			"time":7,
			"day":5
		},
		"$5ส":null,
		null:null
	}
}

function autoRefresh() {
	try {
		document.getElementById("curPeriod").innerHTML = table[new Date().getDay().toString()][Math.floor((new Date().getHours() * 60 + new Date().getMinutes() - 455) / 55)];
	}
	catch (err) {
		document.getElementById("curPeriod").innerHTML = "ไม่มีคาบเรียน";
	}
}
autoRefresh();
setInterval("autoRefresh()", 1000);
